# Generated by Django 3.0.5 on 2020-05-05 19:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trhread',
            new_name='Thread',
        ),
    ]
